### ISSUE TITLE
No package python3-openssl available

### ISSUE THREAD

**Issue by deckardbsd** [weareinteractive/ansible-vsftpd#17]
I've tried to install vsftpd on fedora but I got this message:
`No package python3-openssl available`

The package name is not correct.

**Comment by deckardbsd** [comment]
I think that for redhat familly the correct package name is: "python3-pyOpenSSL".

**Comment by franklinkim** [comment]
Hi, I guess this is more related to the dependent openssl role right?

**Comment by deckardbsd** [comment]
yep, my bad.
