### ISSUE TITLE
The error was: 'openssl_packages' is undefined

### ISSUE THREAD

**Issue by ghachey** [weareinteractive/ansible-vsftpd#18]
Hi. Trying to use this role but need a little help. Not sure if this is the right place to ask. I'm trying with basically the example playbook from the README. I'm getting the following error which looks like it is from the openssl dependency role.

`The task includes an option with an undefined variable. The error was: 'openssl_packages' is undefined`

I need SSL but happy with default OS provided certs. I did try running with the example playbook for weareinteractive.openssl installing some certs and this get rid of the error but I had to run this unecessary weareinteractive.openssl playbook with some mocked up certificates as in the example.

Is there a way to run a weareinteractive.vsftpd with ssl enabled without having to run weareinteractive.openssl setting up my own certificates? (just using the default OS certs)

Thanks for the roles.

**Comment by franklinkim** [comment]
Hi, try to run your playbook with the `--skip-tag openssl-dependency` flag. That should skip the dependency.

**Comment by ghachey** [comment]
Thanks @franklinkim This works nicely. It's unfortunate there is no way to specify this in my playbook. I'd rather not specify this every time I run this playbook. In any case, not a show stopper it still seems to cover my needs well. Thanks.

**Comment by franklinkim** [comment]
@ghachey I will drop the dependency in the future. Have to do a major update / cleanup on all roles once I get the time to do so.

**Comment by ghachey** [comment]
@franklinkim no worries. Looking forward to it. Thanks.
