### ISSUE TITLE
vsftpd_config - YES/NO values converted to boolean value

### ISSUE THREAD

**Issue by staticcat** [weareinteractive/ansible-vsftpd#3]
When using the following configuration object in a playbook. 

```
vsftpd_config:
    log_ftp_protocol=YES
    xferlog_enable=YES
    local_enable=YES
    write_enable=YES
    listen_port=990
    ...
```

The vsftpd.conf file is updated with the following entries. 

```
log_ftp_protocol=True
xferlog_enable=True
local_enable=True
write_enable=True
listen_port=990
...
```

Is there a way around the ansible feature of auto converting the YES/NO strings into boolean values? I found that this is expected behaviour at [ansible issue 11905](https://github.com/ansible/ansible/issues/11905) 

Currently I have just made separate templates for each configuration I would like to run. Is this the best approach.

**Comment by franklinkim** [comment]
hi, first of as a side note:

The `vsftpd_config`variable is currently more or less just a placeholder for setting stuff in the `vsftp.conf` file. At some point there should be a variable like `vsftpd_log_ftp_protocol` for every option but I did this role in a rush and didn't add all variables (PRs more than welcome!)

As for the the bool conversion for this placeholder, the simplest solution I can think of is this:

```
{% for key, value in vsftpd_config.iteritems() %}
{{ key }}={{ {true: "YES", false: "NO"}[value] | default(value) }}
{% endfor %}
```

**Comment by staticcat** [comment]
Thanks, that's great. I will write up something tomorrow and submit.
