### ISSUE TITLE
suggestion to add package manager variable 

### ISSUE THREAD

**Issue by rca0** [weareinteractive/ansible-vsftpd#7]

**Comment by franklinkim** [comment]
Hi, I switch to use the `package` module, so this should fix that.

**Comment by rca0** [comment]
Good, It's better now!!!
I didnt see the parameter `gather_facts` which is set to true, indeed, `ansible_pkg_mgr` will grab the value from the operation system.
Becouse of this, i closed this suggestion but i think you can always improve, your commit is good..
